# Site settings
title: Rohan Sachdeva
description: A blog about Rohan Sachdeva
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rohan Sachdeva
user_description: Hello I am Rohan Sachdeva, I am a B.Tech IT student in VIT University Vellore. I'm a workaholic and I strive to contribute to this world through my knowledge. I'm gourmand by passion and software developer by choice. Friends find me affable which makes me approachable and cooperative. I aspire to be prompt, sincere and creative in my work. I spend my leisure time watching movies, bike riding, playing cricket, badminton, swimming and browsing Quora and Youtube. I also enjoy clicking pictures, few stills are here in the link.
user_technical: My technical interests include programming in C, Java, SQL I practice coding challenges on HackerRank  in the same language and sometimes prefer C++ . For web technology I have basics of HTML, CSS, JavaScript, Servlets and PHP. I have started learning the concepts of BIG Data using Hadoop framework and have implemented few algorithms in the same.
user_title: Software Developer
email: rohan231094@gmail.com
twitter_username: rohan23oct
github_username:  RohanKumarSachdeva
gplus_username:  100821444782706218427
linkedin_username: rohan-sachdeva-5b1701b9/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
